### ISSUE TITLE
Not spawning on an island

### ISSUE THREAD

**Issue by TribalTree123** [MeinKraft/StompBlock-Revamped#13]
**Version of pack: 1.14 or 1.15**
1.16
**Describe the bug**
You don't spawn on an island, it's just the normal world gen

**Expected behavior**
To spawn on an island

**Screenshots**
![image](https://user-images.githubusercontent.com/75741274/101645439-ab35b200-3a36-11eb-95cb-5c44dc696d2b.png)

**Comment by MeinKraft** [comment]
You have to manually set the world type to Garden Of Glass, theres nothing I can do to make it automatic
